rem
rem shopco_create.sql - Creates schema objects for the SHOPCO (Shop Company)
rem practice schema, used for teaching SQL / database management.
rem
rem This script is called from shopco_install.sql and assumes the session's
rem CURRENT_SCHEMA is already set to SHOPCO.
rem --------------------------------------------------------------------------

SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 100
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

Prompt ******  Creating CATEGORIES table ....

CREATE TABLE categories
(
  category_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  category_name   VARCHAR2(100 CHAR) NOT NULL,
  description     VARCHAR2(500 CHAR)
);

Prompt ******  Creating SUPPLIERS table ....

CREATE TABLE suppliers
(
  supplier_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  supplier_name   VARCHAR2(150 CHAR) NOT NULL,
  contact_email   VARCHAR2(255 CHAR),
  country         VARCHAR2(100 CHAR)
);

Prompt ******  Creating CUSTOMERS table ....

CREATE TABLE customers
(
  customer_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email_address   VARCHAR2(255 CHAR) NOT NULL,
  full_name       VARCHAR2(255 CHAR) NOT NULL,
  phone           VARCHAR2(30 CHAR),
  signup_date     DATE DEFAULT SYSDATE NOT NULL
);

Prompt ******  Creating STORES table ....

CREATE TABLE stores
(
  store_id            INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  store_name          VARCHAR2(255 CHAR) NOT NULL,
  web_address         VARCHAR2(200 CHAR),
  physical_address    VARCHAR2(500 CHAR),
  latitude            NUMBER(9,6),
  longitude           NUMBER(9,6),
  opened_date         DATE
);

Prompt ******  Creating EMPLOYEES table ....

CREATE TABLE employees
(
  employee_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  full_name       VARCHAR2(255 CHAR) NOT NULL,
  email_address   VARCHAR2(255 CHAR) NOT NULL,
  job_title       VARCHAR2(100 CHAR) NOT NULL,
  hire_date       DATE NOT NULL,
  store_id        INTEGER,
  manager_id      INTEGER,
  salary          NUMBER(10,2)
);

Prompt ******  Creating PRODUCTS table ....

CREATE TABLE products
(
  product_id        INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  product_name      VARCHAR2(255 CHAR) NOT NULL,
  category_id       INTEGER NOT NULL,
  unit_price        NUMBER(10,2) NOT NULL,
  description       VARCHAR2(500 CHAR),
  active_flag       CHAR(1) DEFAULT 'Y' NOT NULL
);

Prompt ******  Creating REVIEWS table ....

CREATE TABLE reviews
(
  review_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  product_id    INTEGER NOT NULL,
  customer_id   INTEGER NOT NULL,
  rating        NUMBER(2,0) NOT NULL,
  review_text   VARCHAR2(1000 CHAR),
  review_date   DATE DEFAULT SYSDATE NOT NULL
);

Prompt ******  Creating PRODUCT_SUPPLIERS table ....

CREATE TABLE product_suppliers
(
  product_id     INTEGER NOT NULL,
  supplier_id    INTEGER NOT NULL,
  supply_price   NUMBER(10,2) NOT NULL
);

Prompt ******  Creating ORDERS table ....

CREATE TABLE orders
(
  order_id       INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_tms      TIMESTAMP NOT NULL,
  customer_id    INTEGER NOT NULL,
  employee_id    INTEGER NOT NULL,
  store_id       INTEGER NOT NULL,
  order_status   VARCHAR2(10 CHAR) NOT NULL
);

Prompt ******  Creating ORDER_ITEMS table ....

CREATE TABLE order_items
(
  order_id       INTEGER NOT NULL,
  line_item_id   INTEGER NOT NULL,
  product_id     INTEGER NOT NULL,
  unit_price     NUMBER(10,2) NOT NULL,
  quantity       INTEGER NOT NULL,
  shipment_id    INTEGER
);

Prompt ******  Creating SHIPMENTS table ....

CREATE TABLE shipments
(
  shipment_id        INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  store_id           INTEGER NOT NULL,
  customer_id        INTEGER NOT NULL,
  delivery_address   VARCHAR2(500 CHAR) NOT NULL,
  shipment_status    VARCHAR2(20 CHAR) NOT NULL
);

Prompt ******  Creating INVENTORY table ....

CREATE TABLE inventory
(
  inventory_id        INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  store_id            INTEGER NOT NULL,
  product_id          INTEGER NOT NULL,
  product_inventory   INTEGER NOT NULL,
  reorder_level        INTEGER DEFAULT 10 NOT NULL
);

Prompt ******  Creating PAYMENTS table ....

CREATE TABLE payments
(
  payment_id       INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_id         INTEGER NOT NULL,
  payment_date     DATE NOT NULL,
  payment_method   VARCHAR2(30 CHAR) NOT NULL,
  amount           NUMBER(10,2) NOT NULL
);

rem ********************************************************************
rem Create views

Prompt ******  Creating views ....

CREATE OR REPLACE VIEW customer_order_summary AS
  SELECT o.order_id, o.order_tms, o.order_status,
         c.customer_id, c.email_address, c.full_name,
         SUM ( oi.quantity * oi.unit_price ) order_total,
         LISTAGG (
           p.product_name, ', '
           ON OVERFLOW TRUNCATE '...' WITH COUNT
         ) WITHIN GROUP ( ORDER BY oi.line_item_id ) items
  FROM   orders o
  JOIN   order_items oi ON o.order_id = oi.order_id
  JOIN   customers c    ON o.customer_id = c.customer_id
  JOIN   products p     ON oi.product_id = p.product_id
  GROUP  BY o.order_id, o.order_tms, o.order_status,
         c.customer_id, c.email_address, c.full_name;

CREATE OR REPLACE VIEW store_sales_summary AS
  SELECT CASE
           grouping_id ( s.store_name, o.order_status )
           WHEN 1 THEN 'STORE TOTAL'
           WHEN 2 THEN 'STATUS TOTAL'
           WHEN 3 THEN 'GRAND TOTAL'
         END total,
         s.store_name,
         o.order_status,
         COUNT ( DISTINCT o.order_id ) order_count,
         SUM ( oi.quantity * oi.unit_price ) total_sales
  FROM   stores s
  JOIN   orders o       ON s.store_id = o.store_id
  JOIN   order_items oi ON o.order_id = oi.order_id
  GROUP  BY GROUPING SETS (
    ( s.store_name ),
    ( s.store_name, o.order_status ),
    ( o.order_status ),
    ()
  );

CREATE OR REPLACE VIEW product_ratings AS
  SELECT p.product_name,
         ROUND ( AVG ( r.rating ), 2 ) avg_rating,
         COUNT ( r.review_id ) review_count
  FROM   products p
  JOIN   reviews r ON r.product_id = p.product_id
  GROUP  BY p.product_name;

CREATE OR REPLACE VIEW employee_hierarchy AS
  SELECT employee_id, full_name, job_title, manager_id,
         LEVEL emp_level,
         LPAD ( ' ', 2 * ( LEVEL - 1 ) ) || full_name org_chart,
         SYS_CONNECT_BY_PATH ( full_name, ' > ' ) reporting_path
  FROM   employees
  START WITH manager_id IS NULL
  CONNECT BY PRIOR employee_id = manager_id;

rem ********************************************************************
rem Create indexes

Prompt ******  Creating indexes ...

CREATE INDEX customers_name_i            ON customers        ( full_name );
CREATE INDEX products_category_id_i      ON products          ( category_id );
CREATE INDEX reviews_product_id_i        ON reviews           ( product_id );
CREATE INDEX reviews_customer_id_i       ON reviews           ( customer_id );
CREATE INDEX product_suppliers_sup_i     ON product_suppliers ( supplier_id );
CREATE INDEX employees_store_id_i        ON employees         ( store_id );
CREATE INDEX employees_manager_id_i      ON employees         ( manager_id );
CREATE INDEX orders_customer_id_i        ON orders            ( customer_id );
CREATE INDEX orders_employee_id_i        ON orders            ( employee_id );
CREATE INDEX orders_store_id_i           ON orders            ( store_id );
CREATE INDEX shipments_store_id_i        ON shipments         ( store_id );
CREATE INDEX shipments_customer_id_i     ON shipments         ( customer_id );
CREATE INDEX order_items_shipment_id_i   ON order_items       ( shipment_id );
CREATE INDEX inventory_product_id_i      ON inventory         ( product_id );
CREATE INDEX payments_order_id_i         ON payments          ( order_id );

rem ********************************************************************
rem Create constraints

Prompt ******  Adding constraints to tables ...

ALTER TABLE categories ADD CONSTRAINT categories_pk PRIMARY KEY (category_id);
ALTER TABLE categories ADD CONSTRAINT categories_name_u UNIQUE (category_name);

ALTER TABLE suppliers ADD CONSTRAINT suppliers_pk PRIMARY KEY (supplier_id);

ALTER TABLE customers ADD CONSTRAINT customers_pk PRIMARY KEY (customer_id);
ALTER TABLE customers ADD CONSTRAINT customers_email_u UNIQUE (email_address);

ALTER TABLE stores ADD CONSTRAINT stores_pk PRIMARY KEY (store_id);
ALTER TABLE stores ADD CONSTRAINT stores_name_u UNIQUE (store_name);
ALTER TABLE stores ADD CONSTRAINT stores_at_least_one_address_c
  CHECK ( web_address IS NOT NULL OR physical_address IS NOT NULL );

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY (employee_id);
ALTER TABLE employees ADD CONSTRAINT employees_email_u UNIQUE (email_address);
ALTER TABLE employees ADD CONSTRAINT employees_store_id_fk
  FOREIGN KEY (store_id) REFERENCES stores (store_id);
ALTER TABLE employees ADD CONSTRAINT employees_manager_id_fk
  FOREIGN KEY (manager_id) REFERENCES employees (employee_id);

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY (product_id);
ALTER TABLE products ADD CONSTRAINT products_category_id_fk
  FOREIGN KEY (category_id) REFERENCES categories (category_id);
ALTER TABLE products ADD CONSTRAINT products_active_flag_c
  CHECK ( active_flag IN ('Y','N') );

ALTER TABLE reviews ADD CONSTRAINT reviews_pk PRIMARY KEY (review_id);
ALTER TABLE reviews ADD CONSTRAINT reviews_product_id_fk
  FOREIGN KEY (product_id) REFERENCES products (product_id);
ALTER TABLE reviews ADD CONSTRAINT reviews_customer_id_fk
  FOREIGN KEY (customer_id) REFERENCES customers (customer_id);
ALTER TABLE reviews ADD CONSTRAINT reviews_rating_c
  CHECK ( rating BETWEEN 1 AND 10 );

ALTER TABLE product_suppliers ADD CONSTRAINT product_suppliers_pk
  PRIMARY KEY (product_id, supplier_id);
ALTER TABLE product_suppliers ADD CONSTRAINT product_suppliers_product_fk
  FOREIGN KEY (product_id) REFERENCES products (product_id);
ALTER TABLE product_suppliers ADD CONSTRAINT product_suppliers_supplier_fk
  FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id);

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY (order_id);
ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fk
  FOREIGN KEY (customer_id) REFERENCES customers (customer_id);
ALTER TABLE orders ADD CONSTRAINT orders_employee_id_fk
  FOREIGN KEY (employee_id) REFERENCES employees (employee_id);
ALTER TABLE orders ADD CONSTRAINT orders_store_id_fk
  FOREIGN KEY (store_id) REFERENCES stores (store_id);
ALTER TABLE orders ADD CONSTRAINT orders_status_c
  CHECK ( order_status IN ('CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED') );

ALTER TABLE shipments ADD CONSTRAINT shipments_pk PRIMARY KEY (shipment_id);
ALTER TABLE shipments ADD CONSTRAINT shipments_store_id_fk
  FOREIGN KEY (store_id) REFERENCES stores (store_id);
ALTER TABLE shipments ADD CONSTRAINT shipments_customer_id_fk
  FOREIGN KEY (customer_id) REFERENCES customers (customer_id);
ALTER TABLE shipments ADD CONSTRAINT shipments_status_c
  CHECK ( shipment_status IN ('CREATED','SHIPPED','IN-TRANSIT','DELIVERED') );

ALTER TABLE order_items ADD CONSTRAINT order_items_pk PRIMARY KEY (order_id, line_item_id);
ALTER TABLE order_items ADD CONSTRAINT order_items_order_id_fk
  FOREIGN KEY (order_id) REFERENCES orders (order_id);
ALTER TABLE order_items ADD CONSTRAINT order_items_shipment_id_fk
  FOREIGN KEY (shipment_id) REFERENCES shipments (shipment_id);
ALTER TABLE order_items ADD CONSTRAINT order_items_product_id_fk
  FOREIGN KEY (product_id) REFERENCES products (product_id);
ALTER TABLE order_items ADD CONSTRAINT order_items_product_u UNIQUE (product_id, order_id);

ALTER TABLE inventory ADD CONSTRAINT inventory_pk PRIMARY KEY (inventory_id);
ALTER TABLE inventory ADD CONSTRAINT inventory_store_product_u UNIQUE (store_id, product_id);
ALTER TABLE inventory ADD CONSTRAINT inventory_store_id_fk
  FOREIGN KEY (store_id) REFERENCES stores (store_id);
ALTER TABLE inventory ADD CONSTRAINT inventory_product_id_fk
  FOREIGN KEY (product_id) REFERENCES products (product_id);

ALTER TABLE payments ADD CONSTRAINT payments_pk PRIMARY KEY (payment_id);
ALTER TABLE payments ADD CONSTRAINT payments_order_id_u UNIQUE (order_id);
ALTER TABLE payments ADD CONSTRAINT payments_order_id_fk
  FOREIGN KEY (order_id) REFERENCES orders (order_id);
ALTER TABLE payments ADD CONSTRAINT payments_method_c
  CHECK ( payment_method IN ('CREDIT_CARD','DEBIT_CARD','PAYPAL','BANK_TRANSFER','CASH') );

rem ********************************************************************
rem Add table and column comments

Prompt ******  Adding table column comments ...

COMMENT ON TABLE categories IS 'Product categories used to classify items in the catalog';
COMMENT ON TABLE suppliers IS 'Companies that supply products to SHOPCO';
COMMENT ON TABLE customers IS 'Details of the people placing orders';
COMMENT ON TABLE stores IS 'Physical and virtual locations where people can purchase products';
COMMENT ON TABLE employees IS 'Staff members, including the reporting hierarchy via manager_id';
COMMENT ON TABLE products IS 'Details of goods that customers can purchase';
COMMENT ON TABLE reviews IS 'Customer reviews and ratings left for products';
COMMENT ON TABLE product_suppliers IS 'Which suppliers provide each product, and at what cost';
COMMENT ON TABLE orders IS 'Details of who made purchases, where, and who processed them';
COMMENT ON TABLE order_items IS 'Line items purchased within each order';
COMMENT ON TABLE shipments IS 'Details of where ordered goods are delivered';
COMMENT ON TABLE inventory IS 'Stock levels of each product at each store';
COMMENT ON TABLE payments IS 'Payment collected for each order';

COMMENT ON COLUMN orders.order_status IS 'Valid values: OPEN, PAID, SHIPPED, COMPLETE, CANCELLED, REFUNDED';
COMMENT ON COLUMN shipments.shipment_status IS 'Valid values: CREATED, SHIPPED, IN-TRANSIT, DELIVERED';
COMMENT ON COLUMN employees.manager_id IS 'Self-referencing FK to employees.employee_id; NULL for the top of the hierarchy';
